language: scala
cache:
  directories:
  - "$HOME/.ivy2/cache"
  - "$HOME/.sbt/boot/"
jdk:
  - oraclejdk8
before_install:
  - echo "deb https://dl.bintray.com/sbt/debian /" | sudo tee -a /etc/apt/sources.list.d/sbt.list
  - sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 2EE0EA64E40A89B84B2DF73499E82A75642AC823
  - sudo apt-get update
#  - sudo apt-get install sbt
before_script:
  - curl -O https://gist.githubusercontent.com/EmilDafinov/c874e7f3abe77dd770c2bd26828b9224/raw/f75b659d1a2c3634140eace2c7899dc634e2790b/travis_bintray_credentials.sh &&
    chmod +x travis_bintray_credentials.sh &&
    ./travis_bintray_credentials.sh
  - sbt dynverAssertVersion
script:
    sbt clean test publish #Publish artifacts
notifications:
  email: false
